use ark_ff::PrimeField;
/// To see the code generated by the macro, run the following command in the sumcheck_macro directory:
/// ```sh
/// cargo expand --example expand
/// ```
use ark_std::rand::rngs::OsRng;
use dp_crypto::{
    util::{AdditiveArray, ceil_log2, largest_even_below},
    virtual_poly::VirtualPolynomial,
    virtual_polys::PolyMeta,
};

#[derive(Default)]
struct Container<'a, F: PrimeField> {
    poly: VirtualPolynomial<'a, F>,
    is_main_worker: bool,
    phase2_numvar: Option<usize>,
}

type F = ark_bn254::Fq;

fn main() {
    let c = Container::<F>::new();
    c.run();
}

impl<F: PrimeField> Container<'_, F> {
    pub fn run(&self) {
        let poly = &self.poly.flattened_ml_extensions;
        let _result =
            sumcheck_macro::sumcheck_code_gen!(3, false, |_| &poly[0], || PolyMeta::Normal);
    }

    pub fn expected_numvars_at_round(&self) -> usize {
        1
    }

    pub fn new() -> Self {
        Self {
            poly: VirtualPolynomial::random(&[3], (4, 5), 2, &mut OsRng).0,
            is_main_worker: true,
            phase2_numvar: Some(1),
        }
    }
}
