use ark_ff::PrimeField;
use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::{virtual_poly::VirtualPolynomial, virtual_polys::PolyMeta};

/// An IOP proof is a collections of
/// - messages from prover to verifier at each round through the interactive protocol.
/// - a point that is generated by the transcript for evaluation
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(bound(
    serialize = "F: ark_serialize::CanonicalSerialize",
    deserialize = "F: ark_serialize::CanonicalDeserialize"
))]
pub struct IOPProof<F: PrimeField> {
    pub proofs: Vec<IOPProverMessage<F>>,
}

impl<F: PrimeField> IOPProof<F> {
    pub fn extract_sum(&self) -> F {
        self.proofs[0].evaluations[0] + self.proofs[0].evaluations[1]
    }
}

/// A message from the prover to the verifier at a given round
/// is a list of evaluations.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(bound(
    serialize = "F: ark_serialize::CanonicalSerialize",
    deserialize = "F: ark_serialize::CanonicalDeserialize"
))]
pub struct IOPProverMessage<F: PrimeField> {
    #[serde(with = "crate::serialization")]
    pub evaluations: Vec<F>,
}

/// Prover State of a PolyIOP.
#[derive(Default)]
pub struct IOPProverState<'a, F: PrimeField> {
    pub is_main_worker: bool,
    /// sampled randomness given by the verifier
    pub challenges: Vec<F>,
    /// the current round number
    pub(crate) round: usize,
    /// pointer to the virtual polynomial
    pub(crate) poly: VirtualPolynomial<'a, F>,
    pub(crate) max_num_variables: usize,
    pub(crate) poly_meta: Vec<PolyMeta>,
    /// phase 1 and phase 2 sumcheck we share similar implementation
    /// thus this option variable only use for phase 1 sumcheck to mark how many variables belongs to phase 2
    pub(crate) phase2_numvar: Option<usize>,
}

/// Prover State of a PolyIOP
pub struct IOPVerifierState<F: PrimeField> {
    pub(crate) round: usize,
    pub(crate) num_vars: usize,
    pub(crate) max_degree: usize,
    pub(crate) finished: bool,
    /// a list storing the univariate polynomial in evaluation form sent by the
    /// prover at each round
    pub(crate) polynomials_received: Vec<Vec<F>>,
    /// a list storing the randomness sampled by the verifier at each round
    pub(crate) challenges: Vec<F>,
}

/// A SumCheckSubClaim is a claim generated by the verifier at the end of
/// verification when it is convinced.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct SumCheckSubClaim<F: PrimeField> {
    /// the multi-dimensional point that this multilinear extension is evaluated
    /// to
    pub point: Vec<F>,
    /// the expected evaluation
    pub expected_evaluation: F,
}

#[derive(Clone, Debug, Error)]
pub enum VerifierError {
    #[error("Claim not match: expect: {0:?}, got: {1:?}")]
    ClaimNotMatch(String, String),
}
